%%{init: {'theme': 'neutral'}}%%
flowchart TD
    Start([Mulai]) --> Input[Menerima Permintaan List Destinasi berdasarkan Kategori]
    Input --> API[/HTTP Method GET </br> Endpoint: /destinations?category=/]
    
    subgraph "Proses Menampilkan Destinasi Wisata berdasarkan Kategori"
        API --> CheckCat{Kategori Terdaftar?}
        
        CheckCat -- Ya --> Fetch[Kueri Destinasi berdasarkan Kategori]
        Fetch --> CheckData{Data Ditemukan?}
        
    end

    CheckCat -- Tidak --> Error422[Response 404 Notfound: Kategori Tidak Ada]
    CheckData -- Tidak --> Error404[Response 404 Not Found: Destinasi Kosong]
    CheckData -- Ya --> Success200[Response 200 OK: Daftar Destinasi Kategori]
    
    Success200 --> End([Selesai])
    Error422 --> End
    Error404 --> End